version: "3.8"

include:
  - ./web-ui/docker-compose.yaml
  - ./web-api/docker-compose.yaml
  - ./route_management/docker-compose.yaml
  - ./mongodb/docker-compose.yaml

networks:
  shared-net: {}

volumes:
  mongo-volume:
    driver: local